name: Link Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install linkchecker
        run: |
          sudo apt-get update -y; sudo apt-get install -y ruby-full
          gem install html-proofer
      - name: Run link check
        run: |
          htmlproofer --check-external --allow-hash --disable-external --verbose ./ || true
